server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lianxi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #   url:jdbc:mysql://58.87.85.198/lianxi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


mybatis:
  mapperLocations: classpath:mapper/*.xml
  #config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.ali.springboot_mybatis.pojo


